apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  serviceAccountName: jenkins # Specify the ServiceAccount here
  containers:
  - name: jenkins-container
    image: ibrahimelmsery1/jenkins-docker-kubectl:latest
    ports:
    - containerPort: 8080
   