apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
      - name: jenkins
        image: ibrahimelmsery1/jenkins-docker-kubectl:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: jenkins-home
          mountPath: /var/jenkins_home  
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: jenkins-home
        hostPath:
          path: /my-own-Jenkins #you can change it to your own path # you must create this path before apply the deployment    
